CREATE TABLE IF NOT EXISTS plans (
  id BIGSERIAL PRIMARY KEY,
  code VARCHAR(100) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  billing_cycle VARCHAR(50),
  price_cents BIGINT DEFAULT 0,
  features JSONB DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS organization_members (
  id BIGSERIAL PRIMARY KEY,
  org_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'MEMBER',
  department VARCHAR(100),
  status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
  joined_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS teams (
  id BIGSERIAL PRIMARY KEY,
  org_id BIGINT NOT NULL,
  name VARCHAR(255) NOT NULL
);
