apiVersion: v1
kind: Secret
metadata:
  name: nfc-backend-secrets
type: Opaque
stringData:
  db-user: replace-with-db-user
  db-password: replace-with-db-password
  jwt-secret: replace-with-strong-jwt-secret
